import { readdirSync, readFileSync } from 'node:fs';
import { basename, extname, resolve } from 'node:path';
import { openRuntimeDb } from '../../db/client';
import { mapAgentRow, mapAgentTransitionRow, mapRunAttemptRow } from '../../db/mappers';
import type { AgentKind, AgentRecord, AgentTransitionRecord, HarnessKind, RunAttemptRecord, SeedAgentsOptions } from '../../domain/types';
import { now, randomId } from '../../utils/common';
import { emitEvent } from '../events';

const defaultObjective = (slug:string) => `Run ${slug} as a focused agent with one explicit objective.`;
const transitionName = 'default transition';
export function builtInAgentSeedDir() { return resolve(process.cwd(), 'db-seeds', 'agents'); }
function ensureDefaultTransition(db:any, agent:AgentRecord) {
  const existing=mapAgentTransitionRow(db.query('select * from agent_transitions where source_agent_id=? and name=?').get(agent.id,transitionName)); if(existing) return existing;
  const ts=now(); const record:AgentTransitionRecord={id:randomId('transition'),sourceAgentId:agent.id,targetAgentId:null,name:transitionName,description:`Default transition for ${agent.slug}.`,status:'active',transitionObjective:agent.defaultGoal ?? defaultObjective(agent.slug),assignmentMetaJson:'{}',createdAt:ts,updatedAt:ts};
  db.prepare('insert into agent_transitions (id,source_agent_id,target_agent_id,name,description,status,transition_objective,assignment_meta_json,created_at,updated_at) values (?,?,?,?,?,?,?,?,?,?)').run(record.id,record.sourceAgentId,record.targetAgentId,record.name,record.description,record.status,record.transitionObjective,record.assignmentMetaJson,ts,ts);
  emitEvent(db,'agent-transition.seeded','agent-transition',record.id,{sourceAgentId:agent.id}); return record;
}
export function seedBuiltInAgents(home?:string, options:SeedAgentsOptions={}) {
  const db=openRuntimeDb(home); const seeded:AgentRecord[]=[];
  for(const entry of readdirSync(options.definitionsDir ?? builtInAgentSeedDir(),{withFileTypes:true})) { if(!entry.isFile() || extname(entry.name)!=='.json') continue; const raw=JSON.parse(readFileSync(resolve(options.definitionsDir ?? builtInAgentSeedDir(),entry.name),'utf8')); const ts=now(); const seed={id:raw.id,slug:raw.slug ?? basename(entry.name,'.json'),name:raw.name,description:raw.description ?? '',kind:(raw.kind ?? 'system') as AgentKind,status:raw.status ?? 'active',definitionFormat:raw.definitionFormat ?? 'markdown',definitionBody:raw.definitionBody ?? '',defaultGoal:raw.defaultGoal ?? defaultObjective(raw.slug ?? basename(entry.name,'.json')),defaultMetaJson:raw.defaultMetaJson ?? '{}',createdAt:raw.createdAt ?? ts,updatedAt:ts}; const existing=mapAgentRow(db.query('select * from agents where slug=?').get(seed.slug));
    if(existing) db.prepare('update agents set name=?,description=?,kind=?,status=?,definition_format=?,definition_body=?,default_goal=?,default_meta_json=?,updated_at=? where id=?').run(seed.name,seed.description,seed.kind,seed.status,seed.definitionFormat,seed.definitionBody,seed.defaultGoal,seed.defaultMetaJson,ts,existing.id);
    else db.prepare('insert into agents (id,slug,name,description,kind,status,definition_format,definition_body,default_goal,default_meta_json,created_at,updated_at) values (?,?,?,?,?,?,?,?,?,?,?,?)').run(seed.id,seed.slug,seed.name,seed.description,seed.kind,seed.status,seed.definitionFormat,seed.definitionBody,seed.defaultGoal,seed.defaultMetaJson,seed.createdAt,ts);
    const agent=mapAgentRow(db.query('select * from agents where slug=?').get(seed.slug))!; ensureDefaultTransition(db,agent); seeded.push(agent); emitEvent(db,'agent.seeded','agent',agent.id,{slug:agent.slug}); }
  db.close(); return seeded;
}
export function listAgents(home?:string) { const db=openRuntimeDb(home); const rows=db.query('select * from agents order by created_at asc').all().map(mapAgentRow) as AgentRecord[]; db.close(); return rows; }
export function getAgent(id:string,home?:string) { const db=openRuntimeDb(home); const row=mapAgentRow(db.query('select * from agents where id=?').get(id)); db.close(); return row; }
export function getAgentBySlug(slug:string,home?:string) { const db=openRuntimeDb(home); const row=mapAgentRow(db.query('select * from agents where slug=?').get(slug)); db.close(); return row; }
export function createAgentTransition(input:{home?:string;sourceAgentId:string;targetAgentId?:string|null;name:string;description?:string;transitionObjective:string;status?:AgentTransitionRecord['status'];assignmentMeta?:Record<string,unknown>}) { const db=openRuntimeDb(input.home); const ts=now(); const record:AgentTransitionRecord={id:randomId('transition'),sourceAgentId:input.sourceAgentId,targetAgentId:input.targetAgentId ?? null,name:input.name,description:input.description ?? '',status:input.status ?? 'active',transitionObjective:input.transitionObjective,assignmentMetaJson:JSON.stringify(input.assignmentMeta ?? {}),createdAt:ts,updatedAt:ts}; db.prepare('insert into agent_transitions (id,source_agent_id,target_agent_id,name,description,status,transition_objective,assignment_meta_json,created_at,updated_at) values (?,?,?,?,?,?,?,?,?,?)').run(record.id,record.sourceAgentId,record.targetAgentId,record.name,record.description,record.status,record.transitionObjective,record.assignmentMetaJson,ts,ts); emitEvent(db,'agent-transition.created','agent-transition',record.id,{sourceAgentId:record.sourceAgentId,targetAgentId:record.targetAgentId}); db.close(); return record; }
export function listAgentTransitions(home?:string) { const db=openRuntimeDb(home); const rows=db.query('select * from agent_transitions order by created_at asc').all().map(mapAgentTransitionRow) as AgentTransitionRecord[]; db.close(); return rows; }
export function getAgentTransition(id:string,home?:string) { const db=openRuntimeDb(home); const row=mapAgentTransitionRow(db.query('select * from agent_transitions where id=?').get(id)); db.close(); return row; }
export function listAgentTransitionsForAgent(agentId:string,home?:string) { return listAgentTransitions(home).filter(item=>item.sourceAgentId===agentId); }
export function createRunAttempt(input:{home?:string;runId:string;attemptNumber:number;agentId:string;transitionId?:string|null;executionObjective:string;harness:HarnessKind;externalSessionId?:string|null;resumeCommand?:string|null;heartbeatAt?:string|null;hostEnvironmentName?:string|null;workingPath?:string|null;workingPathMode?:string|null;retryFromAttemptId?:string|null;checkpoint?:string|null;sourceGoalSha?:string|null;status?:RunAttemptRecord['status'];debugMeta?:Record<string,unknown>;startedAt?:string|null}) { const db=openRuntimeDb(input.home); const ts=now(); const record:RunAttemptRecord={id:randomId('attempt'),runId:input.runId,attemptNumber:input.attemptNumber,agentId:input.agentId,transitionId:input.transitionId ?? null,status:input.status ?? 'queued',executionObjective:input.executionObjective,harness:input.harness,externalSessionId:input.externalSessionId ?? null,resumeCommand:input.resumeCommand ?? null,heartbeatAt:input.heartbeatAt ?? null,hostEnvironmentName:input.hostEnvironmentName ?? null,workingPath:input.workingPath ?? null,workingPathMode:input.workingPathMode ?? null,retryFromAttemptId:input.retryFromAttemptId ?? null,checkpoint:input.checkpoint ?? null,sourceGoalSha:input.sourceGoalSha ?? null,failureStep:null,statusSnapshotJson:'{}',resultJson:'{}',failureSummary:null,debugMetaJson:JSON.stringify(input.debugMeta ?? {}),startedAt:input.startedAt ?? null,finishedAt:null,createdAt:ts,updatedAt:ts}; db.prepare('insert into run_attempts (id,run_id,attempt_number,agent_id,transition_id,status,execution_objective,harness,external_session_id,resume_command,heartbeat_at,host_environment_name,working_path,working_path_mode,retry_from_attempt_id,checkpoint,source_goal_sha,failure_step,status_snapshot_json,result_json,failure_summary,debug_meta_json,started_at,finished_at,created_at,updated_at) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(record.id,record.runId,record.attemptNumber,record.agentId,record.transitionId,record.status,record.executionObjective,record.harness,record.externalSessionId,record.resumeCommand,record.heartbeatAt,record.hostEnvironmentName,record.workingPath,record.workingPathMode,record.retryFromAttemptId,record.checkpoint,record.sourceGoalSha,record.failureStep,record.statusSnapshotJson,record.resultJson,record.failureSummary,record.debugMetaJson,record.startedAt,record.finishedAt,ts,ts); emitEvent(db,'run-attempt.created','run-attempt',record.id,{runId:record.runId,attemptNumber:record.attemptNumber}); db.close(); return record; }
export function getRunAttempt(id:string,home?:string) { const db=openRuntimeDb(home); const row=mapRunAttemptRow(db.query('select * from run_attempts where id=?').get(id)); db.close(); return row; }
export function listRunAttempts(runId?:string,home?:string) { const db=openRuntimeDb(home); const rows=(runId?db.query('select * from run_attempts where run_id=? order by attempt_number asc').all(runId):db.query('select * from run_attempts order by created_at asc').all()).map(mapRunAttemptRow) as RunAttemptRecord[]; db.close(); return rows; }
export function updateRunAttempt(id:string,input:Partial<Pick<RunAttemptRecord,'status'|'checkpoint'|'workingPath'|'workingPathMode'|'externalSessionId'|'resumeCommand'|'heartbeatAt'|'failureStep'|'failureSummary'|'finishedAt'>> & {result?:Record<string,unknown>;statusSnapshot?:Record<string,unknown>},home?:string) { const current=getRunAttempt(id,home); if(!current) throw new Error(`Run attempt not found: ${id}`); const db=openRuntimeDb(home); db.prepare('update run_attempts set status=?,checkpoint=?,working_path=?,working_path_mode=?,external_session_id=?,resume_command=?,heartbeat_at=?,failure_step=?,failure_summary=?,result_json=?,status_snapshot_json=?,finished_at=?,updated_at=? where id=?').run(input.status ?? current.status,input.checkpoint ?? current.checkpoint,input.workingPath ?? current.workingPath,input.workingPathMode ?? current.workingPathMode,input.externalSessionId ?? current.externalSessionId,input.resumeCommand ?? current.resumeCommand,input.heartbeatAt ?? current.heartbeatAt,input.failureStep ?? current.failureStep,input.failureSummary ?? current.failureSummary,JSON.stringify(input.result ?? JSON.parse(current.resultJson)),JSON.stringify(input.statusSnapshot ?? JSON.parse(current.statusSnapshotJson)),input.finishedAt ?? current.finishedAt,now(),id); db.close(); return getRunAttempt(id,home); }
