import { Form } from "react-router";

import { DurableLink as Link } from "../../../components/durable-link";
import { StatusBadge } from "../../../components/status-badge";
import { eventLabel, goalExecution, parseAttemptSnapshot, relativeTime } from "../model";
import { attemptPath, goalPath, projectPath } from "../navigation";
import type { MissionControlData } from "../server";
import { Icon } from "./icons";

function ViewHeader({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) {
  return <header className="view-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action}</header>;
}

export function AttentionView({ data, filter, projectId }: { data: MissionControlData; filter?: string; projectId?: string }) {
  const records = [
    ...data.queue.reviews.map((item) => ({ type: "review", title: data.goals.find((goal) => goalExecution(data, goal.id).attempts.some((attempt) => attempt.id === item.attempt.id))?.title ?? item.attempt.id, status: "pending review", id: item.attempt.id, body: "Execution evidence requires an operator decision." })),
    ...data.queue.failedAttempts.map((attempt) => ({ type: "failed", title: data.goals.find((goal) => goalExecution(data, goal.id).attempts.some((item) => item.id === attempt.id))?.title ?? attempt.id, status: "failed", id: attempt.id, body: attempt.failureSummary ?? "Execution failed without a summary." })),
    ...data.queue.staleAttempts.map((attempt) => ({ type: "stale", title: attempt.executionObjective, status: "stale", id: attempt.id, body: "Running attempt has no recorded heartbeat." })),
    ...data.queue.dispatchable.map((item) => ({ type: "dispatchable", title: data.goals.find((goal) => goal.id === item.goalId)?.title ?? item.goalId, status: "ready", id: item.goalId, body: "A valid agent transition is ready to dispatch." })),
  ].filter((item) => !filter || item.type === filter);
  return <div className="standard-view"><ViewHeader eyebrow="Decision queue" title="What needs attention now" copy="Exceptions, proof, and consequential decisions—ordered for an operator, not a database." />
    <div className="attention-list">{records.map((item) => <Link key={`${item.type}-${item.id}`} to={item.type === "dispatchable" ? goalPath(projectId ?? "unknown", item.id) : attemptPath(projectId ?? "unknown", item.id)}><i className={item.type}/><div><span>{item.type}</span><h2>{item.title}</h2><p>{item.body}</p></div><StatusBadge value={item.status}/><Icon name="arrow"/></Link>)}{!records.length && <div className="empty-state"><Icon name="check"/><h2>Queue clear</h2><p>Nothing in this category needs intervention.</p></div>}</div>
  </div>;
}

export function GoalsView({ data, projectId, create }: { data: MissionControlData; projectId?: string; create: boolean }) {
  const goals = data.goals.filter((goal) => !projectId || goal.projectId === projectId);
  return <div className="standard-view"><ViewHeader eyebrow="Outcome inventory" title="Goals" copy="Durable requested outcomes, kept separate from every attempt to achieve them." action={projectId?<Link className="primary-action" to={`${projectPath(projectId, "goals")}/new`}><Icon name="plus"/> New goal</Link>:undefined}/>
    {create && projectId && <Form className="create-panel" method="post"><input type="hidden" name="intent" value="create-goal"/><input type="hidden" name="projectId" value={projectId}/><header><div><span>New goal</span><h2>Define the outcome before dispatch.</h2></div><Link to={projectPath(projectId, "goals")}><Icon name="x"/></Link></header><label>Title<input name="title" placeholder="Ship a verifiable outcome" required/></label><div className="form-row"><label>Kind<select name="kind"><option value="feature">Feature</option><option value="bugfix">Bug fix</option><option value="refactor">Refactor</option><option value="maintenance">Maintenance</option><option value="security">Security</option><option value="migration">Migration</option></select></label><label>Initial state<input value="Draft" disabled/></label></div><label>Specification<textarea name="specText" rows={5} placeholder="Expected behavior, constraints, and acceptance criteria"/></label><footer><span>Creation is durable. Dispatch remains a separate decision.</span><button>Create goal</button></footer></Form>}
    {!projectId && <div className="empty-state"><Icon name="target"/><h2>Create a project from the Senderos CLI first</h2><p>Studio can browse the shared system now. A project is required before it can create goals.</p></div>}
    <div className="entity-table"><header><span>Goal</span><span>State</span><span>Execution</span><span>Updated</span></header>{goals.map((goal) => { const execution = goalExecution(data, goal.id); return <Link key={goal.id} to={goalPath(goal.projectId, goal.id)}><div><i className={`kind-dot ${goal.kind}`}/><span><strong>{goal.title}</strong><small>{goal.kind} · {goal.id}</small></span></div><StatusBadge value={goal.status}/><span>{execution.latestAttempt ? `${execution.latestAttempt.harness} · attempt ${execution.latestAttempt.attemptNumber}` : "Not dispatched"}</span><span>{relativeTime(goal.updatedAt)}</span></Link>; })}</div>
  </div>;
}

export function RunsView({ data, attemptId }: { data: MissionControlData; attemptId?: string }) {
  const attempts = [...data.attempts].sort((a,b) => b.createdAt.localeCompare(a.createdAt));
  return <div className="standard-view"><ViewHeader eyebrow="Execution history" title="Runs & attempts" copy="Every logical execution and concrete host attempt, with retries and results preserved." />
    <div className="run-layout"><div className="run-list">{attempts.map((attempt) => { const run=data.runs.find((item)=>item.id===attempt.runId); const goal=data.goals.find((item)=>item.id===run?.goalId); return <Link className={attempt.id===attemptId?"selected":""} key={attempt.id} to={attemptPath(goal?.projectId ?? "unknown", attempt.id)}><i className={`run-state ${attempt.status}`}/><div><strong>{goal?.title ?? attempt.executionObjective}</strong><span>{attempt.id} · attempt {attempt.attemptNumber}</span></div><StatusBadge value={attempt.status}/><time>{relativeTime(attempt.updatedAt)}</time></Link>; })}</div><RunDetail data={data} attemptId={attemptId ?? attempts[0]?.id}/></div>
  </div>;
}

function RunDetail({data,attemptId}:{data:MissionControlData;attemptId?:string}){const attempt=data.attempts.find(i=>i.id===attemptId);if(!attempt)return <div className="empty-state"><h2>No execution history</h2></div>;const run=data.runs.find(i=>i.id===attempt.runId);const goal=data.goals.find(i=>i.id===run?.goalId);const snapshot=parseAttemptSnapshot(attempt.statusSnapshotJson);return <aside className="run-detail"><header><span>Attempt detail</span><StatusBadge value={attempt.status}/></header><h2>{goal?.title}</h2><p>{attempt.executionObjective}</p><dl className="property-list"><div><dt>Harness</dt><dd>{attempt.harness}</dd></div><div><dt>Working path</dt><dd className="mono">{attempt.workingPath??"—"}</dd></div><div><dt>Checkpoint</dt><dd>{attempt.checkpoint??"—"}</dd></div><div><dt>Heartbeat</dt><dd>{relativeTime(attempt.heartbeatAt)}</dd></div><div><dt>Retry from</dt><dd className="mono">{attempt.retryFromAttemptId??"—"}</dd></div></dl><div className="detail-summary"><span>Evidence</span><strong>{snapshot.evidence?.length??0}</strong><span>Review</span><strong>{snapshot.review?.status?.replaceAll("_"," ")??"none"}</strong></div>{attempt.failureSummary&&<div className="failure-callout"><strong>Failure summary</strong><p>{attempt.failureSummary}</p></div>}</aside>}

export function ReviewsView({data}:{data:MissionControlData}){const attempts=data.attempts.filter(a=>{const s=parseAttemptSnapshot(a.statusSnapshotJson);return s.evidence?.length||s.review});return <div className="standard-view"><ViewHeader eyebrow="Quality gate" title="Evidence reviews" copy="Make decisions against concrete proof attached to the exact execution that produced it."/><div className="review-grid">{attempts.map(attempt=>{const s=parseAttemptSnapshot(attempt.statusSnapshotJson);const run=data.runs.find(r=>r.id===attempt.runId);const goal=data.goals.find(g=>g.id===run?.goalId);return <article key={attempt.id}><header><StatusBadge value={s.review?.status??"pending"}/><span>{relativeTime(attempt.updatedAt)}</span></header><h2>{attempt.executionObjective}</h2><p>{s.evidence?.length??0} evidence items · {attempt.harness}</p><Link to={attemptPath(goal?.projectId??"unknown",attempt.id)}>Inspect evidence <Icon name="arrow"/></Link></article>})}</div></div>}

export function AgentsView({data}:{data:MissionControlData}){return <div className="standard-view"><ViewHeader eyebrow="Execution topology" title="Agents & transitions" copy="Persisted roles and the allowed handoffs through which Senderos advances work."/><div className="agent-grid">{data.agents.map(agent=>{const outgoing=data.transitions.filter(t=>t.sourceAgentId===agent.id);return <article key={agent.id}><header><div className="agent-avatar"><Icon name="spark"/></div><StatusBadge value={agent.status}/></header><h2>{agent.name}</h2><p>{agent.description||agent.defaultGoal||"Persisted Senderos executor."}</p><footer><span>{agent.kind}</span><strong>{outgoing.length} transitions</strong></footer></article>})}</div></div>}

export function EventsView({data}:{data:MissionControlData}){return <div className="standard-view"><ViewHeader eyebrow="Append-only history" title="Activity & events" copy="The durable explanation of who changed what, when, and against which orchestration entity."/><div className="events-layout"><div className="event-stream">{[...data.events].reverse().map(event=><article key={event.id}><i/><time>{relativeTime(event.createdAt)}</time><div><strong>{eventLabel(event.eventType)}</strong><span>{event.entityType} · {event.entityId}</span></div><code>{JSON.stringify(event.payload)}</code></article>)}</div><aside className="observability-panel"><header><Icon name="pulse"/><span>Execution signals</span></header><Metric label="Goals" value={data.goals.length}/><Metric label="Runs" value={data.runs.length}/><Metric label="Attempts" value={data.attempts.length}/><Metric label="Retries" value={data.attempts.filter(a=>a.retryFromAttemptId).length}/><Metric label="Evidence" value={data.attempts.reduce((sum,a)=>sum+(parseAttemptSnapshot(a.statusSnapshotJson).evidence?.length??0),0)}/><div className="signal-bars">{["succeeded","running","failed","queued"].map(status=><div key={status}><span>{status}</span><i style={{width:`${Math.max(4,data.attempts.filter(a=>a.status===status).length/Math.max(1,data.attempts.length)*100)}%`}}/></div>)}</div></aside></div></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric-row"><span>{label}</span><strong>{value}</strong></div>}

export function SettingsView({data,projectId}:{data:MissionControlData;projectId?:string}){const project=data.projects.find(p=>p.id===projectId)??data.projects[0];return <div className="standard-view"><ViewHeader eyebrow="Configuration" title="Project & database settings" copy="Repository identity, integration behavior, and the shared database backing this Studio deployment."/>{project&&<Form className="settings-section" method="post"><input type="hidden" name="intent" value="update-project"/><input type="hidden" name="projectId" value={project.id}/><header><div><Icon name="target"/><span><h2>Project</h2><p>Canonical repository and integration behavior.</p></span></div><StatusBadge value={project.status}/></header><div className="settings-fields"><label>Name<input name="name" defaultValue={project.name}/><small>Human-readable project identity.</small></label><label>Repository<input value={`${project.githubOwner}/${project.githubRepo}`} disabled/><small>Canonical GitHub repository.</small></label><label>Target branch<input name="targetBranch" defaultValue={project.targetBranch}/><small>Base branch for planned delivery.</small></label><label>Integration mode<select name="integrationMode" defaultValue={project.integrationMode}><option value="github_pr">GitHub pull request</option><option value="local_merge">Local merge</option></select><small>How completed outcomes integrate.</small></label></div><footer><span>Changes update persisted project configuration.</span><button>Save project</button></footer></Form>}
    <section className="settings-section"><header><div><Icon name="database"/><span><h2>Shared database</h2><p>Studio connects directly; no local Senderos home or config file is required.</p></span></div><span className="connected-label"><i/> Connected</span></header><div className="settings-fields"><Setting label="Endpoint" value={data.runtime.database.endpoint}/><Setting label="Connection mode" value={data.runtime.database.remote?"Remote libSQL":"Local libSQL"}/><Setting label="Database URL variable" value={data.runtime.database.urlEnv}/><Setting label="Auth token variable" value={data.runtime.database.authTokenEnv}/></div></section>
  </div>}
function Setting({label,value}:{label:string;value:string}){return <label>{label}<input value={value} disabled/><small>Loaded from the active Senderos runtime.</small></label>}
